// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbufHHgWwnvPVbucvr0pFSw0zB4Hjahc',
    appId: '1:1040318448307:web:7819f91a6b45313263a6c6',
    messagingSenderId: '1040318448307',
    projectId: 'design-critique-c5f45',
    authDomain: 'design-critique-c5f45.firebaseapp.com',
    storageBucket: 'design-critique-c5f45.firebasestorage.app',
    measurementId: 'G-ZWK0H9HE72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjWvDZpP4x-1OulTUOqLAgFQ4ru-PRMg',
    appId: '1:1040318448307:android:d6233336b4a35e2b63a6c6',
    messagingSenderId: '1040318448307',
    projectId: 'design-critique-c5f45',
    storageBucket: 'design-critique-c5f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5SziOk9mLAMSNcgoGyFTpcUz0YirrbY',
    appId: '1:1040318448307:ios:b9c9173509dd0de963a6c6',
    messagingSenderId: '1040318448307',
    projectId: 'design-critique-c5f45',
    storageBucket: 'design-critique-c5f45.firebasestorage.app',
    iosBundleId: 'com.designcritique.designCritique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO5SziOk9mLAMSNcgoGyFTpcUz0YirrbY',
    appId: '1:1040318448307:ios:b9c9173509dd0de963a6c6',
    messagingSenderId: '1040318448307',
    projectId: 'design-critique-c5f45',
    storageBucket: 'design-critique-c5f45.firebasestorage.app',
    iosBundleId: 'com.designcritique.designCritique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbufHHgWwnvPVbucvr0pFSw0zB4Hjahc',
    appId: '1:1040318448307:web:55e1c73bd3e43ae163a6c6',
    messagingSenderId: '1040318448307',
    projectId: 'design-critique-c5f45',
    authDomain: 'design-critique-c5f45.firebaseapp.com',
    storageBucket: 'design-critique-c5f45.firebasestorage.app',
    measurementId: 'G-SKM63GTR5K',
  );
}
